const mongoose = require('mongoose');

const impliquesSchema = new mongoose.Schema({
  numeroDossier: String,
  sequence: Number,
  codeNature: String,
  codeImplique: String,
  indOrganisme: Boolean,
  nomImplique: String,
  adresse: String,
  municipalite: String,
  codePostal: String,
  codeAvocat: String,
  indFirme: Boolean,
  nomAvocat: String,
  adresseAvocat: String,
  avocatActifCode: String,
  indAvocatActifFirme: Boolean,
  avocatActifNom: String,
  avocatActifAdresse: String,
  montant: Number,
})

const proceduresSchema = new mongoose.Schema({
  numeroDossier: String,
  sequence: Number,
  suffixe: Number,
  codeNature: String,
  procedureEntree: String,
  dateGreffe: String,
  codeProcedure: String,
  descriptionCodeProcedure: String,
  destination: String,
  description: String,
  codeAvocat: String,
  qui: String,
  concerne: String,
  dateProcedure: String,
  numeroReference: String,
  montant: Number,
  codeDocument: String,
  detail: String,
  quiTypeJugement: String,
  quiDisposition: String,
  quiQualiteImplique: String,
  quiNumeroImplique: String,
  quiNomImplique: String,
  quiArticle: String,
  quiL26: String,
  concerneSalleAudition: String,
  concernePrioriteAudition: String,
  concerneHeureAudition: String,
  concerneMinuteAudition: String,
  concerneDateSignificationReqs: String,
  concerneLeReste: String,
  concerneArticle: String,
  detailRelieA: String,
  detailDebutHeure1AuditionAm: String,
  detailDebutHeure2AuditionAm: String,
  detailSequenceProcedure: String,
  detailNumeroDeSalle: String,
  detailDureeJour: String,
  detailDureeHeure: String,
  detailDureeMinute: String,
  detailDateDelai: String,
  detailDelaiEnJour: String,
  detailEnMois: String,
  indFirme: Boolean,
  avocatNom: String,
})

const detailsSchema = new mongoose.Schema({
  numeroDossier: String,
  codeNature: String,
  codeNatureDescription: String,
  dateOuverture: String,
  montant: Number,
  dossierOrigine: String,
  nbrDemandeur: Number,
  nbrDefendeur: Number,
  codeRegion: Number,
  codeDistrict: Number,
  dateActivite: String,
  dossierUlterieur: String,
  nomGreffe: String,
  nomRegion: String,
  nomDistrict: String,
  nomJuridiction: String,
  dateProduction: String,
  adresseGreffe: String,
  municipaliteGreffe: String,
  codePostalGreffe: String,
  indConfidentiel: Boolean,
  dateConfidentiel: String,
  impliquesSchema,
  proceduresSchema,
})

const sejSchema = new mongoose.Schema({
    numeroDossier: String,
    greffe: String,
    juridiction: String,
    annee: String,
    typeStructure: String,
    detailsSchema,
    etatDossier: String,
    dateMAJ: Date
  });

const Dossier = mongoose.model('Dossier', sejSchema)

module.exports = Dossier;